input: ["source"]
output: ["img","filename","fps"]

fps_saved_output_video: 10   #may need to change depending on user machine performance
resize: {
            do_resizing: False,
            width: 1280,
            height: 720
        }
input_source: 0    # 0 for webcam, rtsp URL for CCTV
mirror_image: False