input: ["source"]
output: ["img", "end", "filename", "fps"]

resize: {
            do_resizing: False,
            width: 1280,
            height: 720
        }
input_dir: 'PeekingDuck/data/input'
mirror_image: False