input: ["img"]
output: ["bboxes", "bbox_labels", "bbox_scores"]

weights_parent_dir: null
weights:
  {
    model_subdir: yolov4,
    blob_file: yolo.zip,
    classes_file: coco.names,
    model_file: { v4: yolov4.pb, v4tiny: yolov4-tiny.pb },
  }
input_size: 416
max_output_size_per_class: 50
max_total_size: 50
num_classes: 80
model_nodes: { inputs: [x:0], outputs: [Identity:0] }

model_type: v4tiny # v4 or v4tiny
detect_ids: [0]
iou_threshold: 0.5
score_threshold: 0.2
