pytorch:
      # Options: Accuracy | Precision | Recall | AUROC | CalibrationError
      - Accuracy:
              average: "micro"
      - Precision:
              average: "macro"
      - Recall
      - AUROC:
              average: "weighted"

tensorflow:
      # Options: Accuracy | Precision | Recall | AUC
      - "CategoricalAccuracy"
      - Precision:
              thresholds: 0.5
      - Recall:
              thresholds: 0.5
      - AUC:
              from_logits: False
              multi_label: True
              num_labels: ${data_module.dataset.num_classes}
