input: ["img"]
output: ["bboxes", "labels", "score"]

yolo_graph_mode: True
model_class: humanmodel
model_type: v4tiny # v3, v3tiny, v4 or v4tiny
classes: ../weights/yolov3/models/coco.names
weights_dir: ["../weights/yolov3", "../weights/yolov4"]
weights_id: "1_FFZDDbHgghK23J4ekPhuawMoDd19uQO"
model_files: {
    v3: ../weights/yolov3/models/yolov3.tf,
    v3tiny: ../weights/yolov3/models/yolov3-tiny.tf,
    v4: ../weights/yolov4/yolov4.h5,
    v4tiny: ../weights/yolov4/yolov4-tiny-416
}
graph_files: {
    v3: ../weights/yolov3/yolov3.pb,
    v3tiny: ../weights/yolov3/yolov3-tiny.pb,
    v4: ../weights/yolov4/yolov4.pb,
    v4tiny: ../weights/yolov4/yolov4-tiny.pb
}
size: 416
image: ../weights/yolov3/images/street.jpg
output: ../results/yolov3/output.jpg
num_classes: 80
detect_ids: [0]
yolo_iou_threshold: 0.5
yolo_score_threshold: 0.2
MODEL_NODES: {
    yolov41: {
        inputs: [x:0],
        outputs: [model/tf_op_layer_split_2/split_2:0,
        model/tf_op_layer_split_1/split_1:0,
        model/tf_op_layer_split/split:0,
        Identity:0]
    },
    yolov4: {
        inputs: [x:0],
        outputs: [Identity:0]
    },
    yolov3: {
        inputs: [x:0],
        outputs: [Identity:0]
    }
}