name: Publish to pypi
env:
  VERSION: ${{github.event.release.tag_name}}
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  local-install-test:
    name: Build PeekingDuck and test locally
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Update Version Number
        run: |
          bash ./scripts/update_version.sh $VERSION
      - name: Local Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_cicd.txt
          pip install .
      - name: Local Test
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: |
            bash ./scripts/run_tests.sh all
            bash ./scripts/usecase_tests.sh
  build-publish-test:
    name: Build PeekingDuck on Test PyPI
    needs: local-install-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Update Version Number
        run: |
          bash ./scripts/update_version.sh $VERSION
      - name: Install pypa and build
        run: |
          echo "Building new version..."
          python -m pip install --upgrade pip
          python -m pip install build --user
          python -m build --sdist --wheel --outdir dist/ .
      - name: Publish distribution ðŸ“¦ to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Test installation from Test PyPI
        run: |
          sleep 300
          # need to separately install requirements (from pypi repo), 
          # as some packages are not available on test.pypi.org repo
          # e.g. tqdm 4.45 not available
          pip install -r requirements.txt
          pip install -i https://test.pypi.org/simple/ peekingduck==$VERSION --no-deps
          peekingduck
      - name: Publish distribution ðŸ“¦ to PyPI
        # only pushes to actual PyPI if its a tag (i.e. on release: published)
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  test-install-pypi:
    name: Build PeekingDuck on PyPI
    needs: build-publish-test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Test installation from PyPI
        run: |
          sleep 300
          pip install peekingduck==$VERSION
          peekingduck
